### ISSUE TITLE
I can't access data google link 

### ISSUE THREAD

**Issue by dlsrnsi** [XieResearchGroup/DISAE#1]
Hello, 

I'm trying to fine-tune your model to predict DTI, but I can't access dataset link 

https://drive.google.com/file/d/1o12gyV_YY8E2lWFaqm73xsT5wfpGBsk8/view?usp=sharing

Would you mind checking your dataset link please?

Thank you for reading.

**Comment by lxie21** [comment]
A new link is provided. Please have a check. Sorry for the inconvenience.
